print('введите 2 числа:')
a = int(input())
b = int(input())
print(a - b)
print('Изменение для 2 веток, пункт b, продолжение слияния 2 веток')
print('Change dlya 10 punkta zadaniya dlya maina')
c = int(input())
